### ISSUE TITLE
Setting "done = False" instead of "True"

### ISSUE THREAD

**Issue by ThomasLecat** [JKCooper2/gym-bandits#1]
Hi Jesse,

Thanks a lot for this package !
To train my network on the bandit environments, I would like the "done" indicator to be always False instead of being always True.
I tried to change the value of the variable "done" in gym_bandits/bandits.py to False and reinstalled the package, but it didn't change anything and I still always get "(0, <reward>, True, {})" when performing "env.step(<action>)".

Would you have any idea to fix my problem ?

Thanks again !
Thomas

**Comment by JKCooper2** [comment]
Hi,

Bandit problems are by design single run and require a reset after,

Sent from my iPhone

On 20 Jun 2017, at 4:34 am, "ThomasLecat" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi JKCooper2,

Thanks a lot for this package !
To train my network on the bandit environments, I would like the "done" indicator to be always False instead of being always True.
I tried to change the value of the variable "done" in gym_bandits/bandits.py to False and reinstalled the package, but it didn't change anything and I still always get "(0, , True, {})" when performing "env.step()".

Would you have any idea to fix my problem ?

Thanks again !
Thomas

**Comment by JKCooper2** [comment]
Sorry didn't realise the last email did fully send. I'd suggest altering you're agents behaviour to just ignore the true value for the episode ending. If you've edited the package locally is suggest checking that you're editing the actual library folder location it's loaded from rather than the git repo if you are cloning (eg inside the anaconda folder if you are using that).

Let me know if you need any other info

Jesse

Sent from my iPhone

On 20 Jun 2017, at 4:34 am, "ThomasLecat" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi JKCooper2,

Thanks a lot for this package !
To train my network on the bandit environments, I would like the "done" indicator to be always False instead of being always True.
I tried to change the value of the variable "done" in gym_bandits/bandits.py to False and reinstalled the package, but it didn't change anything and I still always get "(0, , True, {})" when performing "env.step()".

Would you have any idea to fix my problem ?

Thanks again !
Thomas

**Comment by ThomasLecat** [comment]
Thanks Jesse,

I ended up altering the agent to ignore the True value as you said, maybe not the cleanest solution but it works !

Modifying the actual folder location it's loaded from was my initial idea, but when asking python where that folder is (with "import gym_bandits", then "print(gym_bandits.__file__"), it says that the library is loaded directly from the cloned git repo... Maybe I misunderstand something here.

Anyway, thanks again for the answer, my agent is working properly now,

Thomas
